### ISSUE TITLE
Item.WeightInPounds using wrong helper method

### ISSUE THREAD

**Issue by marshalltowncompany** [StephenPAdams/SixFourThree.BoxPacker#1]
Wrong:
        public Double WeightInPounds => ConversionHelper.ConvertPoundsToGrams(Weight);

Should be:
        public Double WeightInPounds => ConversionHelper.ConvertGramsToPounds(Weight);

I tried to make the change, but I don't have permissions.

**Comment by StephenPAdams** [comment]
Hi @marshalltowncompany good catch! I'll go ahead and fix this stat! Thank you!

**Comment by StephenPAdams** [comment]
@marshalltowncompany completed. Thank you!
